version: "3.7"

services:
  ingress:
    image: "ghcr.io/allyusd/sgp1-game/ingress:main"
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
      - 3000:3000
    networks:
      - minesweeper

networks:
  minesweeper:
    name: minesweeper-network
